server:
  port: 8082

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    buckets:
        customer: ${AWS_BUCKET}

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://containers-us-west-49.railway.app:6073/railway
    password: 9CTkX6hlZxUgC9gG3YSY
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
    flyway:
      baselineOnMigrate: true
      user: postgres
      password: 9CTkX6hlZxUgC9gG3YSY
      schemas: public
      createSchemas: true
      locations: classpath:db/migration

    jpa:
      show-sql: true
      hibernate:
        format-sql: true
  messages:
    basename: i18m/messages